nocout/device/urls.py
from django.conf.urls import patterns, url
from device import views, api

#caching GIS maps
from django.views.decorators.cache import cache_page
#caching GIS maps

urlpatterns = patterns('',
  url(r'^$', views.DeviceList.as_view(), name='device_list'),
  url(r'^(?P<pk>\d+)/$', views.DeviceDetail.as_view(), name='device_detail'),
  url(r'^new/$', views.DeviceCreate.as_view(), name='device_new'),
  url(r'^(?P<pk>\d+)/edit/$', views.DeviceUpdate.as_view(), name='device_edit'),
  url(r'^(?P<pk>\d+)/delete/$', views.DeviceDelete.as_view(), name='device_delete'),

  # url(r'^stats/$', cache_page(60 * 60)(api.DeviceStatsApi.as_view())),
  url(r'^stats/$', api.DeviceStatsApi.as_view()),

  #cache the Filters. they dont change
  url(r'^filter/$', cache_page(60 * 60)(api.DeviceFilterApi.as_view())),
  #cache the Filters. they dont change

  url(r'^lp_services/', api.LPServicesApi.as_view()),
  url(r'^lp_service_data/', api.FetchLPDataApi.as_view()),
  url(r'^lp_bulk_data/', api.BulkFetchLPDataApi.as_view()),
  url(r'^ts_templates/', api.FetchThematicSettingsApi.as_view()),
  url(r'^treeview/$', views.create_device_tree, name='device_tree_view'),
  url(r'^operationaldevicelistingtable/', views.OperationalDeviceListingTable.as_view(), name= 'OperationalDeviceListingTable'),
  url(r'^nonoperationaldevicelistingtable/', views.NonOperationalDeviceListingTable.as_view(), name= 'NonOperationalDeviceListingTable'),
  url(r'^disableddevicelistingtable/', views.DisabledDeviceListingTable.as_view(), name= 'DisabledDeviceListingTable'),
  url(r'^archiveddevicelistingtable/', views.ArchivedDeviceListingTable.as_view(), name= 'ArchivedDeviceListingTable'),
  url(r'^alldevicelistingtable/', views.AllDeviceListingTable.as_view(), name= 'AllDeviceListingTable'),
)

nocout/device/models.py
from django.db import models
from machine.models import Machine
from organization.models import Organization
from site_instance.models import SiteInstance
from service.models import Service, ServiceParameters, ServiceDataSource
from mptt.models import MPTTModel


#************************************ Device Inventory**************************************
# table for countries
class Country(models.Model):
    country_name = models.CharField('Name', max_length=200)

    def __unicode__(self):
        return self.country_name


# table for states
class State(models.Model):
    state_name = models.CharField('Name', max_length=200)
    country = models.ForeignKey(Country, null=True, blank=True)

    def __unicode__(self):
        return self.state_name


# table for cities
class City(models.Model):
    city_name = models.CharField('Name', max_length=250)
    state = models.ForeignKey(State, null=True, blank=True)

    def __unicode__(self):
        return self.city_name


# table for state latitude & longitude
class StateGeoInfo(models.Model):
    state = models.ForeignKey(State)
    latitude = models.FloatField('Latitude')
    longitude = models.FloatField('Longitude')


class DeviceFrequency(models.Model):
    value = models.CharField(max_length=50, help_text="MHz")
    color_hex_value = models.CharField(max_length=100)
    frequency_radius = models.FloatField(verbose_name="Frequency Radius", default=0, help_text="Km")

    def __unicode__(self):
        return self.value


# device ports
class DevicePort(models.Model):
    name = models.CharField('Name', max_length=100, unique=True)
    alias = models.CharField('Alias', max_length=200)
    value = models.IntegerField('Port Value', default=0)

    def __unicode__(self):
        return self.name


# device types info table
class DeviceType(models.Model):
    name = models.CharField('Device Type', max_length=200, unique=True)
    alias = models.CharField('Alias', max_length=200)
    device_port = models.ManyToManyField(DevicePort, null=True, blank=True)
    service = models.ManyToManyField(Service, through="DeviceTypeService", blank=True, null=True)
    packets = models.IntegerField('Packets', blank=True, null=True)
    timeout = models.IntegerField('Timeout', blank=True, null=True)
    normal_check_interval = models.IntegerField('Normal Check Interval', blank=True, null=True)
    rta_warning = models.IntegerField('RTA Warning', blank=True, null=True)
    rta_critical = models.IntegerField('RTA Critical', blank=True, null=True)
    pl_warning = models.IntegerField('PL Warning', blank=True, null=True)
    pl_critical = models.IntegerField('PL Critical', blank=True, null=True)
    agent_tag = models.CharField('Agent Tag', max_length=200, null=True, blank=True)
    device_icon = models.ImageField(upload_to='uploaded/icons/%Y/%m/%d')
    device_gmap_icon = models.ImageField(upload_to='uploaded/icons/%Y/%m/%d')

    def __unicode__(self):
        return self.name

    def delete(self, *args, **kwargs):
        """
        Delete method: deletes the device_icon and device_gmap_icon.
        """
        self.device_icon.delete()
        self.device_gmap_icon.delete()
        super(DeviceType, self).delete(*args, **kwargs)


# device type with specific service info table
class DeviceTypeService(models.Model):
    device_type = models.ForeignKey(DeviceType)
    service = models.ForeignKey(Service)
    parameter = models.ForeignKey(ServiceParameters)
    service_data_sources = models.ManyToManyField(ServiceDataSource, through="DeviceTypeServiceDataSource")


# device type with specific service data source info table
class DeviceTypeServiceDataSource(models.Model):
    device_type_service = models.ForeignKey(DeviceTypeService)
    service_data_sources = models.ForeignKey(ServiceDataSource)
    warning = models.CharField('Warning', max_length=255, null=True, blank=True)
    critical = models.CharField('Critical', max_length=255, null=True, blank=True)


# device model info table
class DeviceModel(models.Model):
    name = models.CharField('Device Model', max_length=100, unique=True)
    alias = models.CharField('Alias', max_length=200)
    device_types = models.ManyToManyField(DeviceType, through="ModelType", blank=True, null=True)

    def __unicode__(self):
        return self.name


# device vendor info table
class DeviceVendor(models.Model):
    name = models.CharField('Device Vendor', max_length=100, unique=True)
    alias = models.CharField('Alias', max_length=200)
    device_models = models.ManyToManyField(DeviceModel, through="VendorModel", blank=True, null=True)

    def __unicode__(self):
        return self.name


# device technology info table
class DeviceTechnology(models.Model):
    name = models.CharField('Device Technology', max_length=100, unique=True)
    alias = models.CharField('Alias', max_length=200)
    device_vendors = models.ManyToManyField(DeviceVendor, through="TechnologyVendor", blank=True, null=True)

    def __unicode__(self):
        return self.name


# device info table
class Device(MPTTModel, models.Model):
    enable = 'Enable'
    disable = 'Disable'
    high = 'High'
    normal = 'Normal'
    low = 'Low'

    DHCP_STATE = (
        (enable, 'Enable'),
        (disable, 'Disable'),
    )
    HOST_STATE = (
        (enable, 'Enable'),
        (disable, 'Disable'),
    )
    PRIORITY = (
        (high, 'High'),
        (normal, 'Normal'),
        (low, 'Low')
    )

    device_name = models.CharField('Name', max_length=200, unique=True)
    device_alias = models.CharField('Alias', max_length=200)
    machine = models.ForeignKey(Machine, null=True, blank=True)
    site_instance = models.ForeignKey(SiteInstance, null=True, blank=True)
    organization = models.ForeignKey(Organization)
    device_technology = models.IntegerField('Device Technology')
    device_vendor = models.IntegerField('Device Vendor')
    device_model = models.IntegerField('Device Model')
    device_type = models.IntegerField('Device Type')
    ports = models.ManyToManyField(DevicePort, null=True, blank=True)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='device_children')
    ip_address = models.IPAddressField('IP Address', unique=True)
    mac_address = models.CharField('MAC Address', max_length=100, null=True, blank=True)
    netmask = models.IPAddressField('Netmask', null=True, blank=True)
    gateway = models.IPAddressField('Gateway', null=True, blank=True)
    dhcp_state = models.CharField('DHCP State', max_length=200, choices=DHCP_STATE, default=disable)
    host_priority = models.CharField('Host Priority', max_length=200, choices=PRIORITY, default=normal)
    host_state = models.CharField('Host Monitoring State', max_length=200, choices=HOST_STATE, default=enable)
    latitude = models.FloatField('Latitude', null=True, blank=True)
    longitude = models.FloatField('Longitude', null=True, blank=True)
    timezone = models.CharField('Timezone', max_length=100, default="Asia/Kolkata")
    country = models.IntegerField('Country', null=True, blank=True)
    state = models.IntegerField('State', null=True, blank=True)
    city = models.IntegerField('City', null=True, blank=True)
    address = models.TextField('Address', null=True, blank=True)
    description = models.TextField('Description', null=True, blank=True)
    is_deleted = models.IntegerField('Is Deleted', max_length=1, default=0)
    is_added_to_nms = models.IntegerField('Is Added', max_length=1, default=0)
    is_monitored_on_nms = models.IntegerField('Is Monitored', max_length=1, default=0)

    def __unicode__(self):
        return self.device_alias

    class Meta:
        ordering = ['machine']


# model-type mapper
class ModelType(models.Model):
    model = models.ForeignKey(DeviceModel)
    type = models.ForeignKey(DeviceType)


# vendor-model mapper
class VendorModel(models.Model):
    vendor = models.ForeignKey(DeviceVendor)
    model = models.ForeignKey(DeviceModel)


# technology-vendor mapper
class TechnologyVendor(models.Model):
    technology = models.ForeignKey(DeviceTechnology)
    vendor = models.ForeignKey(DeviceVendor)


# table for extra fields of device (depends upon device type)
class DeviceTypeFields(models.Model):
    field_name = models.CharField(max_length=100)
    field_display_name = models.CharField(max_length=200)
    device_type = models.ForeignKey(DeviceType)

    def __unicode__(self):
        return self.field_display_name


# table for device extra fields values
class DeviceTypeFieldsValue(models.Model):
    device_type_field = models.ForeignKey(DeviceTypeFields)
    field_value = models.CharField(max_length=250)
    device_id = models.IntegerField()

nocout/device/templates/wizard/device_type.html
{% extends "inventory/inventory.html" %}
{% load staticfiles %}

{% block content_title %}Edit Device Type{% endblock %}
{% block content_description %}Edit device type{% endblock %}
{% block content %}
    <div class="row formContainer">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="box border lite">
                        <div class="box-title">
                            <h4><i class="fa fa-bars"></i> GIS WIZARD: DEVICE TYPE</h4>
                        </div>
                            <div class="box-body">
                                <div class="col-md-8"><br />

                {% if form %}
                    <form id="id_device_type_form" action="" method="post" class="form-horizontal" role="form"  enctype="multipart/form-data">{% csrf_token %}
                        {% include "wizard/form.html" with form=form only %}

                        {{ device_type_service_form.management_form }}
                        {% for field in device_type_service_form %}
                            {{ field.id }}
                        <div class="row inline {{ device_type_service_form.prefix }}">
                            <hr>
                            <div id="id_service" class="form-group">
                                <label for="{{ field.id_for_label }}" class="col-sm-3 control-label"><span class="mandatory">*</span> Service</label>
                                <div class="col-sm-9">
                                    <div class="col-md-8">
                                        {{field.service}}{{ device_type_service_form.non_form_errors }}
                                    </div>
                                </div>
                            </div>
                            <div id="id_parameter" class="form-group">
                                <label for="{{ field.id_for_label }}" class="col-sm-3 control-label"><span class="mandatory">*</span> Parameter </label>
                                <div class="col-sm-9">
                                    <div class="col-md-8">
                                        {{field.parameter}}
                                    </div>
                                </div>
                            </div>
                            {{ field.DELETE }}
                        </div>
                        {% endfor %}

                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                <button type="submit" class="btn btn-success"><i class="fa fa-pencil"></i>{{ save_text }} &amp; Next</button>
                                &nbsp;
                                <button type="submit" id="id_update_and_show" class="btn btn-success"><i class="fa fa-pencil"></i>{{ save_text }} &amp; Show</button>
                                {% if skip_url %}
                                &nbsp;
                                <button type="reset" class="btn btn-warning" onclick="window.location.replace('{{ skip_url }}')"><i class="fa fa-times"></i>Skip</button>
                                {% endif %}
                                &nbsp;
                                {% url 'device_type_list' as cancel_url %}
                                <button type="reset" class="btn btn-danger" onclick="window.location.replace('{{ cancel_url }}')"><i class="fa fa-times"></i>Cancel</button>
                            </div>
                        </div>
                    </form>
                {% endif %}
                                </div>
                                <div class="clearfix"></div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block content_js %}
        <script type="text/javascript" src={% static "js/nocout/nocout_forms.js" %}></script>
        <script type="text/javascript" src={% static "js/bootstrap-file-input/bootstrap-file-input.js" %}></script>
        <script type="text/javascript" src={% static "js/jquery.formset.js" %}></script>
    {% endblock %}
    <script>
        $(document).ready(function(){
            $("#id_update_and_show").on("click", function(e) {
                e.preventDefault();
                $('#id_device_type_form').attr('action', "?show=True").submit();
            });

            // Changing labels of form fields
            $("label[for=id_rta_warning]").text('Latency Warning');
            $("label[for=id_rta_critical]").text('Latency Critical');
            $("label[for=id_pl_warning]").text('PD % Warning');
            $("label[for=id_pl_critical]").text('PD % Critical');
            $("label[for=id_packets]").text('Packet Count');
            $("label[for=id_timeout]").text('Timeout (ms)');

            // modify image upload field
            var device_icon = "#id_device_icon";
            var device_gmap_icon = "#id_device_gmap_icon";
            $(device_icon).bootstrapFileInput();
            $(device_icon).prev().text("Search for a file to add");
            $(device_gmap_icon).bootstrapFileInput();
            $(device_gmap_icon).prev().text("Search for a file to add");

            // Initialize the select2 selectbox.
            $(".select2select").select2();
        })

        var dts_value = []
        var dts_value = $('form input[type="hidden"][id|="id_dts"][name|="dts"][name$="id"][value]')

        // if service is already selected
        if ($("#id_service").find("option:selected").val()){
            var service = $("form").find(".row").find("#id_service").slice(dts_value.length)
            service.each(function() {
              var service_id = $(this).find("option:selected").val()
              var parameter = $(this).parent(".row .inline").find("#id_parameter")

              get_attribute_of_service(service_id, parameter)
            });
        }

        // if service is changed by the user
        $("form").find(".row").find("#id_service").change(function(){
            var service_id = $(this).find("option:selected").val()
            var parameter = $(this).parent(".row .inline").find("#id_parameter")

            get_attribute_of_service(service_id, parameter)
        });

        function get_attribute_of_service(service_id, parameter){
            var service_counter = service_counter - 1
            if(service_id == '' ){
                console.log('Select the service')
            }
            else{
                $.ajax({
                    url : "/service/select/",
                    type : "GET",
                    dataType: "json",
                    data: {
                        service_id : service_id,
                    },
                    success : function(service) {
                        var parameter_option = parameter.find("select option:selected")
                        parameter_option.val(service.parameters_id)
                        parameter_option.html(service.parameters_name)
                    },
                    error : function(xhr,errmsg,err) {
                        console.log(xhr.status + ": " + xhr.responseText);
                    }
                });

                return false;
            }
        }

    </script>
    <script type="text/javascript">
       $(function() {
           $(".inline.{{ device_type_service_form.prefix }}").formset({
               prefix: "{{ device_type_service_form.prefix }}",
           })
       })
    </script>
{% endblock %}

nocout/device/templates/wizard/device_type_service_update.html
{% extends "inventory/inventory.html" %}
{% load staticfiles %}

{% block content_title %}Edit Device Type Service{% endblock %}
{% block content_description %}Edit device type service{% endblock %}
{% block content %}
    <div class="row formContainer">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="box border lite">
                        <div class="box-title">
                            <h4><i class="fa fa-bars"></i> GIS WIZARD: DEVICE TYPE SERVICE</h4>
                        </div>
                            <div class="box-body">
                                <div class="col-md-8"><br />

                {% if form %}
                    <form id="id_device_type_service_form" action="" method="post" class="form-horizontal" role="form"  enctype="multipart/form-data">{% csrf_token %}
                        {% include "wizard/form.html" with form=form only %}

                        {{ dts_data_source_form.management_form }}
                        {% for form in dts_data_source_form %}
                        <div class="row inline {{ dts_data_source_form.prefix }}">
                            {{form.id}}
                            <div class="form-group">
                                <label for="{{ form.id_for_label }}" class="col-sm-3 control-label"><span class="mandatory">*</span> Service Data Sources</label>
                                <div id="id_service_data_source" class="col-sm-9">
                                    <div class="col-md-7">
                                        {{form.service_data_sources}} {{ dts_data_source_form.non_form_errors }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="{{ form.id_for_label }}" class="col-sm-3 control-label">Warning</label>
                                <div class="col-sm-9">
                                    <div class="col-md-7">
                                        {{form.warning}}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="{{ form.id_for_label }}" class="col-sm-3 control-label">Critical</label>
                                <div class="col-sm-9">
                                    <div class="col-md-7">
                                        {{form.critical}}
                                    </div>
                                </div>
                            </div>
                            {{ form.DELETE }}
                        </div>
                        {% endfor %}


                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                <button type="submit" class="btn btn-success"><i class="fa fa-pencil"></i>{{ save_text }} &amp; Next</button>
                                &nbsp;
                                <button type="submit" id="id_update_and_show" class="btn btn-success"><i class="fa fa-pencil"></i>{{ save_text }} &amp; Show</button>
                                {% if skip_url %}
                                &nbsp;
                                <button type="reset" class="btn btn-warning" onclick="window.location.replace('{{ skip_url }}')"><i class="fa fa-times"></i>Skip</button>
                                {% endif %}
                                &nbsp;
                                {% url 'device_type_list' as cancel_url %}
                                <button type="reset" class="btn btn-danger" onclick="window.location.replace('{{ cancel_url }}')"><i class="fa fa-times"></i>Cancel</button>
                            </div>
                        </div>
                    </form>
                {% endif %}
                                </div>
                                <div class="clearfix"></div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block content_js %}
        <script type="text/javascript" src={% static "js/nocout/nocout_forms.js" %}></script>
        <script type="text/javascript" src={% static "js/bootstrap-file-input/bootstrap-file-input.js" %}></script>
        <script type="text/javascript" src={% static "js/jquery.formset.js" %}></script>
        <script type="text/javascript" src={% static "js/jquery-validate/jquery.validate.min.js" %}></script>
    {% endblock %}
    <script>
        $(document).ready(function(){
            $("#id_update_and_show").on("click", function(e) {

                e.preventDefault();
                if ($("#id_device_type_service_form").valid()) {
                    $('#id_device_type_service_form').attr('action', "?show=True").submit();
                } else {
                    alert('Please fill both warning and critical fields. Or leave both empty.');
                }
            });

            // Initialize the select2 selectbox.
            $(".select2select").select2();
        })

        // if service is changed by the user
        $("#id_service").change(function(){
            if($(this).val() == '' ){
                console.log('Select the service')
            }
            else{
                $.ajax({
                    url : "/service/select/",
                    type : "GET",
                    dataType: "json",
                    data: {
                        service_id : $(this).val(),
                    },
                    success : function(service) {
                        $("#id_parameter option:selected").val(service.parameters_id)
                        $("#id_parameter option:selected").html(service.parameters_name).change()
                    },
                    error : function(xhr,errmsg,err) {
                        console.log(xhr.status + ": " + xhr.responseText);
                    }
                });

                return false;
            }
        });

        // if service data source is already selected.
        var sds = $("form").find(".row").find("#id_service_data_source")
        if (sds.length){
            sds.each(function() {
            var sds_id = $(this).find("option:selected").val()
            var sds_location = $(this).parents(".row .inline")
            get_sds_value(sds_id, sds_location)
            })
        }

        // if the service data source is changed by the user.
        sds.change(function(){
            var sds_id = $(this).find("option:selected").val()
            var sds_location = $(this).parents(".row .inline")
            get_sds_value(sds_id, sds_location)
        })

        //  Get the value of the data source selected by the user.
        //  An display the warning & critical values selected of service data source in brackets.
        function get_sds_value(sds_id, sds_location){
            var sds_id = sds_id
            if (!sds_id.length){
                console.log("No service data source is selected")
            }
            else{
                $.ajax({
                    url : "/service/select/value/data_source/",
                    type : "GET",
                    dataType: "json",
                    data: {
                        sds_id : sds_id,
                    },
                    success : function(sds) {
                        var p = sds_location.children().slice(2)
                        var w = sds.sds_values_list[0]['warning']
                        var c = sds.sds_values_list[0]['critical']
                        // if the data source is empty
                        if (!w.length){ w = null }
                        if (!c.length){ c = null }
                        p.find('[id|="id_dtsds"][id$="value"]').remove()
                        p.first().find('input').parent().append('<label id="id_dtsds-value">( '+w+' )</label>')

                        p.first().next().find('input').parent().append('<label id="id_dtsds-value">( '+c+' )</label>')
                    },
                    error : function(xhr,errmsg,err) {
                        console.log(xhr.status + ": " + xhr.responseText);
                    }
                });

                return false;
            }
        }


        // get all the input field of the service data source to implement the validation
        // warning and critical: both should contain value or both should be null.
        sds_fields = $("form input[class='form-control'][id|='id_dtsds'][name|='dtsds'][type='text']")
        sds_fields.change(function(){
            var ele = $(this).attr('name')  // input field warning/critical
            var ele_val = $(this).val()     // get the value of input field
            if (ele.indexOf('warning')>0){
                var c = $(this).parent().parent().parent().next().find('input[name$="critical"]')
                if (ele_val.length || c.val() ){
                    $(this).prop('required', true)
                    c.prop('required', true);
                }
                else{
                    $(this).prop('required', false)
                    c.prop('required', false);
                }
            }
            else{
                var w = $(this).parent().parent().parent().prev().find('input[name$="warning"]')
                if (ele_val.length || w.val() ){
                    $(this).prop('required', true)
                    w.prop('required', true);
                }
                else{
                    $(this).prop('required', false)
                    w.prop('required', false);
                }
            }
        });

    </script>
    <script type="text/javascript">
       $(function() {
           $(".inline.{{ dts_data_source_form.prefix }}").formset({
               prefix: "{{ dts_data_source_form.prefix }}",
           })
       })
    </script>
{% endblock %}

nocout/device/templates/wizard/form.html
<div class="form-group">
    {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}" class="col-sm-3 control-label">{% if field.field.required %}<span class="mandatory">* </span>{% endif %}{{ field.label|title }}</label>
            <div class="col-sm-9">
                <div class="col-md-8">
                    {{ field }} {{ field.errors }}
                </div>
                <div class="col-md-4 help_text">
                    {# field.help_text #}
                </div>
            </div>
        </div>
    {% endfor %}
</div>

nocout/device/templates/wizard/service_list.html
{% extends "nocout/base.html" %}
{% load staticfiles %}

{% block content_title %}Service Listing{% endblock %}
{% block content_description %}List of service{% endblock %}
{% block content %}

        <div class="box border lite">
        <div id="tableContainer_div" class="box-title">
            <h4><i class="fa fa-table"></i> SERVICE LISTING <a href="{% url 'wizard-device-type-update' pk=device_type.id %}">( {{device_type|upper}} )</a></h4>
{#            <div class="tools hidden-xs">#}
{#                <a href="#box-config" data-toggle="modal" class="config">#}
{#                    <i class="fa fa-cog"></i>#}
{#                </a>#}
{#                <a href="javascript:;" class="reload">#}
{#                    <i class="fa fa-refresh"></i>#}
{#                </a>#}
{#            </div>#}
        </div>

        <div id="tableContainer" class="box-body">
            <table cellpadding="0" cellspacing="0" border="0" class="datatable table table-striped table-bordered table-hover" id="wizard-service-list-table">
                <thead></thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block jquery %}
    <script type="text/javascript" src={% static "js/utils/jqueryDataTable.js" %}></script>
    <script type="text/javascript">
        $(document).ready(function (e) {
            /*Make a instance of ourDataTableWidget class */
            var dataTableInstance = new ourDataTableWidget();
            /*Grid headers object*/
            var gridHeadersObj = $.parseJSON('{{ datatable_headers|safe }}');
            /*Ajax url to get grid data*/
            var ajax_url = '{% url "wizard-service-list-table" dt_pk=device_type.id %}';
            /*Call createDataTable function of ourDataTableWidget class*/
            var destroy=false;
            dataTableInstance.createDataTable("wizard-service-list-table", gridHeadersObj, ajax_url, destroy);
        });
    </script>
{% endblock %}