nocout/user_profile/urls.py
from django.conf.urls import patterns, url
from user_profile import views

urlpatterns = patterns('',
  url(r'^$', views.UserList.as_view(), name='user_list'),
  url(r'^(?P<pk>\d+)/$', views.UserDetail.as_view(), name='user_detail'),
  url(r'^new/$', views.UserCreate.as_view(), name='user_new'),
  url(r'^(?P<pk>\d+)/edit/$', views.UserUpdate.as_view(), name='user_edit'),
  url(r'^(?P<pk>\d+)/delete/$', views.UserDelete.as_view(), name='user_delete'),
  url(r'^myprofile/', views.CurrentUserProfileUpdate.as_view(), name='current_user_profile_update'),
  url(r'userlistingtable/', views.UserListingTable.as_view(), name= 'UserListingTable'),
  url(r'userarchivedlistingtable/', views.UserArchivedListingTable.as_view(), name= 'UserArchivedListingTable'),
  url(r'organisation/user/list/$', views.organisation_user_list, name= 'organisation-user-list'),
  url(r'organisation/user/select/$', views.organisation_user_select, name= 'organisation-user-select'),
  url(r'change_password/$', views.change_password, name= 'change_password'),
)

nocout/user_profile/models.py
from django.db import models
from django.contrib.auth.models import User, UserManager
from mptt.models import MPTTModel, TreeForeignKey
from organization.models import Organization


# user profile class
class UserProfile(MPTTModel, User):
    """
    user Profile columns declared
    """
    parent = TreeForeignKey('self', null=True, blank=True, related_name='user_children')
    role = models.ManyToManyField('Roles')
    organization = models.ForeignKey(Organization)
    phone_number = models.CharField('Phone No.', max_length=15, null=True, blank=True)
    company = models.CharField('Company', max_length=100, null=True, blank=True)
    designation = models.CharField('Designation', max_length=100, null=True, blank=True)
    address = models.CharField('Address', max_length=150, null=True, blank=True)
    comment = models.TextField('Comment', null=True, blank=True)
    is_deleted = models.IntegerField('Is Deleted', max_length=1, default=0)
    password_changed_at = models.DateTimeField('Password changed at', null=True, blank=True)
    user_invalid_attempt = models.IntegerField('Invalid attempt', null=True, blank=True, default=0)
    user_invalid_attempt_at = models.DateTimeField('Invalid attemp at', null=True, blank=False)

# user roles class
class Roles(models.Model):
    """
    User Roles columns declared.
    """
    role_name = models.CharField('Role Name', max_length=100, null=True, blank=True)
    role_description = models.CharField('Role Description', max_length=250, null=True, blank=True)

    def __unicode__(self):
        return self.role_description

class UserPasswordRecord(models.Model):
    """
    To keep the record of the password used by user.
    """
    user_id = models.IntegerField('User Id', null=True, blank=True)
    password_used = models.CharField('Password', max_length=100, null=True, blank=True)
    password_used_on = models.DateTimeField('Password Used On', auto_now_add=True)

nocout/user_profile/templates/user_profile/parent_list_option.html
<option value=>Select</option>
{% for choice_tuple in user_choices %}
    {% if choice_tuple.0 %}
        <option value={{ choice_tuple.0 }}>{{ choice_tuple.1 }}</option>
    {% endif %}
{% endfor %}

nocout/user_profile/templates/user_profile/user_delete.html
{% extends "department/department.html" %}

{% block content_title %}Delete User{% endblock %}
{% block content_description %}Delete user{% endblock %}
{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm"/>
    </form>
{% endblock %}

nocout/user_profile/templates/user_profile/user_detail.html
{% extends "department/department.html" %}
{% load staticfiles %}

{% block content_title %}User Detail{% endblock %}
{% block content_description %}Detail of user{% endblock %}
{% block content %}
    <style type="text/css">
        #user_profile table tr td:first-child {
            font-weight: bold;
        }
        #user_profile table tr td {
            font-weight: normal;
        }
    </style>
    <div class="box border lite">
        <div id="tableContainer_div" class="box-title">
            <h4><i class="fa fa-table"></i> USER Detail - {{ object.username }}</h4>

            <div class="tools hidden-xs">
                <a href="#box-config" data-toggle="modal" class="config">
                    <i class="fa fa-cog"></i>
                </a>
                <a href="javascript:;" class="reload">
                    <i class="fa fa-refresh"></i>
                </a>
            </div>
        </div>
        <div class="box-body">
            <div id="user_profile" class="col-md-6 col-md-offset-3">
                <table class="table table-hover table-bordered">
                    <tr>
                        <td><i class="fa fa-arrow-right text-primary"></i> First Name</td>
                        <td>{{ object.first_name }}</td>
                    </tr>
                    <tr>
                        <td><i class="fa fa-arrow-right text-primary"></i> Last Name</td>
                        <td>{{ object.last_name }}</td>
                    </tr>
                    <tr>
                        <td><i class="fa fa-arrow-right text-primary"></i> Email</td>
                        <td>{{ object.email }}</td>
                    </tr>
                    <tr>
                        <td><i class="fa fa-arrow-right text-primary"></i> Role</td>
                        <td>
                            {% for role in object.role.all %}
                                {{ role }}
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <td><i class="fa fa-arrow-right text-primary"></i> Parent</td>
                        <td>{{ object.parent }}</td>
                    </tr>
                    <tr>
                        <td><i class="fa fa-arrow-right text-primary"></i> User Group</td>
                        <td>
                            {% for department in object.department_set.all %}
                                {{ department.user_group }}
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <td><i class="fa fa-arrow-right text-primary"></i> Company</td>
                        <td>{{ object.company }}</td>
                    </tr>
                    <tr>
                        <td><i class="fa fa-arrow-right text-primary"></i> Designation</td>
                        <td>{{ object.designation }}</td>
                    </tr>
                    <tr>
                        <td><i class="fa fa-arrow-right text-primary"></i> Phone Number</td>
                        <td>{{ object.phone_number }}</td>
                    </tr>
                    <tr>
                        <td><i class="fa fa-arrow-right text-primary"></i> Address</td>
                        <td>{{ object.address }}</td>
                    </tr>
                    <tr>
                        <td><i class="fa fa-arrow-right text-primary"></i> Created On</td>
                        <td>{{ object.date_joined }}</td>
                    </tr>
                    <tr>
                        <td><i class="fa fa-arrow-right text-primary"></i> Last Login</td>
                        <td>{{ object.last_login }}</td>
                    </tr>
                </table>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
{% endblock %}

nocout/user_profile/templates/user_profile/user_myprofile.html
{% extends "department/department.html" %}
{% load staticfiles %}

{% block content_title %}Edit User Profile{% endblock %}
{% block content_description %}Edit user profile{% endblock %}
{% block content %}
    <div class="row formContainer">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="box border lite">
                        <div class="box-title">
                            <h4><i class="fa fa-bars"></i> EDIT USER : {{ object.username }}</h4>
                        </div>
                            <div class="box-body">
                                <div class="col-md-8"><br />
                                    <form action="" method="post" class="form-horizontal" role="form" autocomplete="off">{% csrf_token %}
                                        <div class="form-group">
                                            {% for field in form %}
                                                <div class="form-group">
                                                    <label for="{{ field.id_for_label }}" class="col-sm-3 control-label">{% if field.field.required %}<span class="mandatory">* </span>{% endif %}{{ field.label|title }}</label>
                                                    <div class="col-sm-9">
                                                        <div class="col-md-8">
                                                            {{ field }} {{ field.errors }}
                                                        </div>
                                                        <div class="col-md-4 help_text">
                                                            {{ field.help_text }}
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                        <div class="form-group">
                                            <div class="col-sm-offset-3 col-sm-9">
                                                <button type="submit" class="btn btn-info"><i class="fa fa-edit"></i>Update</button>
                                                &nbsp;
                                                <button type="reset" class="btn btn-danger" onclick="window.location.replace('/user/')"><i class="fa fa-times"></i> Cancel</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block content_js %}
        <script type="text/javascript" src={% static "js/nocout/nocout_forms.js" %}></script>
    {% endblock %}
    <script>
        $(document).ready(function(){
            // Initialize the select2 selectbox.
            $(".select2select").select2();
        })
    </script>
{% endblock %}

nocout/user_profile/templates/user_profile/user_new.html
{% extends "department/department.html" %}
{% load staticfiles %}

{% block content_title %}Add User{% endblock %}
{% block content_description %}Add user{% endblock %}
{% block content %}
    <div class="row formContainer">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="box border lite">
                        <div class="box-title">
                            <h4><i class="fa fa-bars"></i> ADD USER</h4>
                        </div>
                            <div class="box-body">
                                <div class="col-md-8"><br />
                                    <form action="/user/new/" method="post" class="form-horizontal" role="form" autocomplete="off">{% csrf_token %}
                                        <div class="form-group">
                                            {% for field in form %}
                                                <div class="form-group">
                                                    <label for="{{ field.id_for_label }}" class="col-sm-3 control-label">{% if field.field.required %}<span class="mandatory">* </span>{% endif %}{{ field.label|title }}</label>
                                                    <div class="col-sm-9">
                                                        <div class="col-md-8">
                                                            {{ field }} {{ field.errors }}
                                                        </div>
                                                        <div class="col-md-4 help_text">
                                                            {{ field.help_text }}
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                        <div class="form-group">
                                            <div class="col-sm-offset-3 col-sm-9">
                                                <button type="submit" class="btn btn-success"><i class="fa fa-pencil"></i>Create</button>
                                                &nbsp;
                                                <button type="reset" class="btn btn-warning" onclick="resetForm();"><i class="fa fa-refresh"></i>Reset</button>
                                                &nbsp;
                                                <button type="reset" class="btn btn-danger" onclick="window.location.replace('/user/')"><i class="fa fa-times"></i>Cancel</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block content_js %}
        <script type="text/javascript" src={% static "js/nocout/nocout_forms.js" %}></script>
    {% endblock %}
    <script>
        $(document).ready(function(){
            // Initialize the select2 selectbox.
            $(".select2select").select2();

            //Check weather the organization and parent is selected or not
            if ($("#id_organization").val() == "") {
                $("#id_parent").empty();
            }
            else if ($("#id_parent").val() == ""){
                $("#id_parent").empty();
                list_parent_according_to_organisation()
            }
            else{
                select_parent_already_selected()
            }

            //on change of the organisation list the parent list.
            $('#id_organization').change(function(){
                list_parent_according_to_organisation()
            })

            //function to get the list of the parent according to the ogranisation.
            function list_parent_according_to_organisation(){
                var organisation_id = $('#id_organization option:selected').val()
                console.log(parent)
                //if no organisation is selected.
                if(organisation_id == '' ){
                    $('#id_parent').html("<option value=>Select</option>").change();
                }
                else{
                    $.ajax({
                        url : "/user/organisation/user/list/",
                        type : "GET",
                        dataType: "html",
                        data: {
                            organisation_id : organisation_id
                        },
                        success : function(parent_list_option) {
                            $('#id_parent').html(parent_list_option);
                            $('#id_parent').change();
                        },
                        error : function(xhr,errmsg,err) {
                            console.log(xhr.status + ": " + xhr.responseText);
                        }
                    });
                    return false;
                }
            }

            function select_parent_already_selected(){
                var organization_id = $('#id_organization option:selected').val()
                var parent_id = $('#id_parent option:selected').val()
                //if no organisation is selected.
                if(organization_id == '' ){
                    $('#id_parent').html("<option value=>Select</option>").change();
                }
                else{
                    $.ajax({
                        url : "/user/organisation/user/select/",
                        type : "GET",
                        dataType: "html",
                        data: {
                            parent_id : parent_id,
                        },
                        success : function(parent_select) {
                            $('#id_parent').empty();
                            $('#id_parent').html(parent_select);
                        },
                        error : function(xhr,errmsg,err) {
                            console.log(xhr.status + ": " + xhr.responseText);
                        }
                    });
                    return false;
                }
            }
        })
    </script>
{% endblock %}

nocout/user_profile/templates/user_profile/user_update.html
{% extends "department/department.html" %}
{% load staticfiles %}

{% block content_title %}Edit User{% endblock %}
{% block content_description %}Edit user{% endblock %}
{% block content %}
    <div class="row formContainer">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="box border lite">
                        <div class="box-title">
                            <h4><i class="fa fa-bars"></i> EDIT USER : {{ object.username }}</h4>
                        </div>
                            <div class="box-body">
                                <div class="col-md-8"><br />
                                    <form action="" method="post" class="form-horizontal" role="form" autocomplete="off">{% csrf_token %}
                                        <div class="form-group">
                                            {% for field in form %}
                                                <div class="form-group">
                                                    <label for="{{ field.id_for_label }}" class="col-sm-3 control-label">{% if field.field.required %}<span class="mandatory">* </span>{% endif %}{{ field.label|title }}</label>
                                                    <div class="col-sm-9">
                                                        <div class="col-md-8">
                                                            {{ field }} {{ field.errors }}
                                                        </div>
                                                        <div class="col-md-4 help_text">
                                                            {{ field.help_text }}
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                        <div class="form-group">
                                            <div class="col-sm-offset-3 col-sm-9">
                                                <button type="submit" class="btn btn-info"><i class="fa fa-edit"></i> Update</button>
                                                &nbsp;
                                                <button type="reset" class="btn btn-danger" onclick="window.location.replace('/user/')"><i class="fa fa-times"></i> Cancel</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block content_js %}
        <script type="text/javascript" src={% static "js/nocout/nocout_forms.js" %}></script>
    {% endblock %}
    <script>
        $(document).ready(function(){
            // Initialize the select2 selectbox.
            $(".select2select").select2();

            //Check weather the organization and parent is selected or not
            if ($("#id_organization").val() == "") {
                $("#id_parent").empty();
            }
            else if ($("#id_parent").val() == ""){
                $("#id_parent").empty();
                list_parent_according_to_organisation()
            }
            else{
                select_parent_already_selected()
            }

            //on change of the organisation list the parent list.
            $('#id_organization').change(function(){
                list_parent_according_to_organisation()
            })

            //function to get the list of the parent according to the ogranisation.
            function list_parent_according_to_organisation(){
                var organisation_id = $('#id_organization option:selected').val()
                //if no organisation is selected.
                if(organisation_id == '' ){
                    $('#id_parent').html("<option value=>Select</option>").change();
                }
                else{
                    $.ajax({
                        url : "/user/organisation/user/list/",
                        type : "GET",
                        dataType: "html",
                        data: {
                            organisation_id : organisation_id
                        },
                        success : function(parent_list_option) {
                            $('#id_parent').html(parent_list_option);
                            $('#id_parent').change();
                        },
                        error : function(xhr,errmsg,err) {
                            alert(xhr.status + ": " + xhr.responseText);
                        }
                    });
                    return false;
                }
            }

            function select_parent_already_selected(){
                var organization_id = $('#id_organization option:selected').val()
                var parent_id = $('#id_parent option:selected').val()
                //if no organisation is selected.
                if(organization_id == '' ){
                    $('#id_parent').html("<option value=>Select</option>").change();
                }
                else{
                    $.ajax({
                        url : "/user/organisation/user/select/",
                        type : "GET",
                        dataType: "html",
                        data: {
                            parent_id : parent_id,
                        },
                        success : function(parent_select) {
                            $('#id_parent').empty();
                            $('#id_parent').html(parent_select);
                        },
                        error : function(xhr,errmsg,err) {
                            console.log(xhr.status + ": " + xhr.responseText);
                        }
                    });
                    return false;
                }
            }
        })
    </script>
{% endblock %}

nocout/user_profile/templates/user_profile/users_list.html
{% extends "department/department.html" %}
{% load staticfiles %}

{% block content_title %}Users Management{% endblock %}
{% block content_description %}List of users{% endblock %}
{% block content %}
    {% for group in user.groups.all %}
        {% if group.name == 'group_admin' %}
            <p><a href="/user/new"><i class="fa fa-plus">&nbsp;</i> Create User</a></p>
        {% endif %}
    {% endfor %}
    <div class="box border lite">
    <div id="tableContainer_div" class="box-title">
        <h4><i class="fa fa-table"></i>USER LISTING</h4>
    </div>
    <div class="box-body">
        <div class="tabbable header-tabs">
            <ul class="nav nav-tabs">
                <li><a href="#UserArchivedListing" id="userArchived_tab" data-toggle="tab"><span class="hidden-inline-mobile">Archived User Listing</span></a></li>
                <li class="active"><a href="#UserListing" id="user_tab" data-toggle="tab"><span class="hidden-inline-mobile">User Listing</span></a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane in active" id="UserListing">
                    <table id="UserListingTable" cellpadding="0" cellspacing="0" border="0" class="datatable table table-striped table-bordered table-hover">
                        <thead></thead>
                        <tbody></tbody>
                    </table>
                </div>
                <div class="tab-pane" id="UserArchivedListing">
                    <table id="UserArchivedListingTable" cellpadding="0" cellspacing="0" border="0" class="datatable table table-striped table-bordered table-hover">
                        <thead></thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{#    </div>#}
{% endblock %}

{% block jquery %}
    <!-- Custom script for data table-->
    <script type="text/javascript" src={% static "js/utils/jqueryDataTable.js" %}></script>
    <!-- Library to load tab content on tab click-->
    <script type="text/javascript" src={% static "js/nocout/openTabContentLib.js" %}></script>
    <!-- Custom Script for soft delete-->
    <script type="text/javascript" src={% static "js/nocout/softDeleteLib.js" %}></script>
    <script type="text/javascript">

        var dataTableInstance = "";

        $(document).ready(function (e) {

            /*Make a instance of ourDataTableWidget class */
            dataTableInstance = new ourDataTableWidget();

            /*Grid headers object*/
            // var gridHeadersObj = $.parseJSON('{{ datatable_headers|safe }}');

            /*Ajax url to get grid data*/
            var ajax_url_user_listing = '{% url "UserListingTable" %}' + '?datatable_headers=' + encodeURIComponent('{{ datatable_headers|safe }}');

            var ajax_url_user_archived_listing = '{% url "UserArchivedListingTable" %}';

            /*Add custom attributes for ajax_url & grid header to the tab i.e 'a' tag.*/

            $("#userArchived_tab").attr("data_url",ajax_url_user_archived_listing);
            $("#userArchived_tab").attr("data_header",'{{ datatable_headers|safe }}');

            $("#user_tab").attr("data_url",ajax_url_user_listing);
            $("#user_tab").attr("data_header",'{{ datatable_headers|safe }}');

            var location_array = window.location.href.split("#");

            if((location_array.length > 1 && location_array[1] == "") || (location_array.length == 1)) {

                /*Trigger click event on active tab to load its data*/
                $("#user_tab").trigger('click',true);
            }

            /*Call createDataTable function of ourDataTableWidget class*/
            // dataTableInstance.createDataTable("UserListingTable", gridHeadersObj, ajax_url_user_listing, destroy = false);
            // dataTableInstance.createDataTable("UserArchivedListingTable", gridHeadersObj, ajax_url_user_archived_listing, destroy = false);
        });
    </script>
{% endblock %}