nocout/service/urls.py
from django.conf.urls import patterns, url
from service import views

urlpatterns = patterns('',
  url(r'^$', views.ServiceList.as_view(), name='services_list'),
  url(r'^(?P<pk>\d+)/$', views.ServiceDetail.as_view(), name='service_detail'),
  url(r'^new/$', views.ServiceCreate.as_view(), name='service_new'),
  url(r'^(?P<pk>\d+)/edit/$', views.ServiceUpdate.as_view(), name='service_edit'),
  url(r'^(?P<pk>\d+)/delete/$', views.ServiceDelete.as_view(), name='service_delete'),
  url(r'^servicelistingtable/', views.ServiceListingTable.as_view(), name='ServiceListingTable'),
  url(r'^select/$', views.select_service, name='select-service'),
  url(r'^select/value/data_source/$', views.select_value_data_source, name='select-value-data-source'),
)

nocout/service/models.py
from django.db import models
from command.models import Command
from datetime import datetime


class Protocol(models.Model):
    """
    Protocol Model Columns declaration
    """
    name = models.CharField('Parameters Name', max_length=255)
    protocol_name = models.CharField('Protocol Name', max_length=255)
    port = models.IntegerField('Port')
    version = models.CharField('Version', max_length=10)
    read_community = models.CharField('Read Community', max_length=100)
    write_community = models.CharField('Write Community', max_length=100, blank=True, null=True)
    auth_password = models.CharField('Auth Password', max_length=100, blank=True, null=True)
    auth_protocol = models.CharField('Auth Protocol', max_length=100, blank=True, null=True)
    security_name = models.CharField('Security Name', max_length=100, blank=True, null=True)
    security_level = models.CharField('Security Level', max_length=100, blank=True, null=True)
    private_phase = models.CharField('Private Phase', max_length=100, blank=True, null=True)
    private_pass_phase = models.CharField('Private Pass Phase', max_length=100, null=True, blank=True)

    def __unicode__(self):
        """
        Protocol Object presentation
        """
        return self.name


class ServiceDataSource(models.Model):
    """
    Service Data Source Model Columns declaration
    """
    name = models.CharField('Name', max_length=100)
    alias = models.CharField('Alias', max_length=250)
    warning = models.CharField('Warning', max_length=255, null=True, blank=True)
    critical = models.CharField('Critical', max_length=255, null=True, blank=True)

    def __unicode__(self):
        """
        Service Data Source Object presentation
        """
        return self.name


class ServiceParameters(models.Model):
    """
    Service Parameters Model Columns Declaration.
    """
    parameter_description = models.CharField(max_length=250)
    protocol = models.ForeignKey(Protocol, verbose_name=" SNMP Parameters")
    normal_check_interval = models.IntegerField()
    retry_check_interval = models.IntegerField()
    max_check_attempts = models.IntegerField()

    '''
    max_check_attempts = models.IntegerField()
    check_interval = models.IntegerField()
    retry_interval = models.IntegerField(null=True, blank=True)
    check_period = models.CharField(max_length=100, null=True, blank=True)
    notification_interval = models.IntegerField(null=True, blank=True)
    notification_period = models.CharField(max_length=100, null=True, blank=True)  # timeperiod_name
    is_volatile = models.IntegerField(null=True, blank=True)
    initial_state = models.CharField(max_length=1, null=True, blank=True)                              # [o,w,u,c]
    active_checks_enabled = models.IntegerField(null=True, blank=True)                                 # [0/1]
    passive_checks_enabled = models.IntegerField(null=True, blank=True)                                # [0/1]
    obsess_over_service = models.IntegerField(null=True, blank=True)                                   # [0/1]
    check_freshness = models.IntegerField(null=True, blank=True)                                       # [0/1]
    freshness_threshold = models.CharField(max_length=100, null=True, blank=True)
    event_handler = models.CharField(max_length=100, null=True, blank=True)
    event_handler_enabled = models.IntegerField()                                                      # [0/1]
    low_flap_threshold = models.CharField(max_length=100, null=True, blank=True)
    high_flap_threshold = models.CharField(max_length=100, null=True, blank=True)
    flap_detection_enabled = models.IntegerField(null=True, blank=True)                                # [0/1]
    flap_detection_options = models.CharField(max_length=100, null=True, blank=True)                   # [o,w,c,u]
    process_perf_data = models.CharField(max_length=100, null=True, blank=True)                        # [0/1]
    retain_status_information = models.IntegerField(null=True, blank=True)                             # [0/1]
    retain_nonstatus_information = models.IntegerField(null=True, blank=True)                          # [0/1]
    first_notification_delay = models.IntegerField(null=True, blank=True)
    notification_options = models.CharField(max_length=1, null=True, blank=True)                       # [w,u,c,r,f,s]
    notifications_enabled = models.IntegerField(null=True, blank=True)
    stalking_options = models.CharField(max_length=1, null=True, blank=True)                           # [o,w,u,c]
    notes = models.CharField(max_length=100, null=True, blank=True)
    notes_url = models.URLField(max_length=200, null=True, blank=True)
    action_url = models.URLField(max_length=200, null=True, blank=True)
    '''

    def __unicode__(self):
        """
        Service Parameters object presentation.
        """
        return self.parameter_description


class Service(models.Model):
    """
    Service Model Column Declaration.
    """
    name = models.CharField('Name', max_length=100)
    alias = models.CharField('Alias', max_length=100)
    parameters = models.ForeignKey(ServiceParameters)
    service_data_sources = models.ManyToManyField(ServiceDataSource, through="ServiceSpecificDataSource")
    command = models.ForeignKey(Command, null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def __unicode__(self):
        """
        Service object presentation
        """
        return self.name


class ServiceSpecificDataSource(models.Model):
    """
    Service Based Data Source Model Column Declaration.
    """
    service_data_sources = models.ForeignKey(ServiceDataSource)
    service = models.ForeignKey(Service)
    warning = models.CharField('Warning', max_length=255, null=True, blank=True)
    critical = models.CharField('Critical', max_length=255, null=True, blank=True)


# device service configuration --> it contains services those are already running
class DeviceServiceConfiguration(models.Model):
    """
    Device Service Configuration Model Declaration.
    """
    device_name = models.CharField('Device Name', max_length=200, null=True, blank=True)
    service_name = models.CharField('Service Name', max_length=200, null=True, blank=True)
    agent_tag = models.CharField('Agent Tag', max_length=50, null=True, blank=True)
    port = models.IntegerField('Port', null=True, blank=True)
    data_source = models.CharField('Data Source', max_length=200, null=True, blank=True)
    version = models.CharField('Version', max_length=10, blank=True, null=True)
    read_community = models.CharField('Read Community', max_length=100, blank=True, null=True)
    svc_template = models.CharField('Service Template', max_length=200, blank=True, null=True)
    normal_check_interval = models.IntegerField('Normal Check Interval', null=True, blank=True)
    retry_check_interval = models.IntegerField('Retry Check Interval', null=True, blank=True)
    max_check_attempts = models.IntegerField('Max Check Attempts', null=True, blank=True)
    warning = models.CharField('Warning', max_length=20, null=True, blank=True)
    critical = models.CharField('Critical', max_length=20, null=True, blank=True)
    added_on = models.DateTimeField('Added On', null=True, blank=True)
    modified_on = models.DateTimeField('Modified On', null=True, blank=True)
    is_added = models.IntegerField('Is Added', default=0)

    class Meta:
        ordering = ["added_on"]

    def save(self, *args, **kwargs):
        """ On save, update timestamps """
        if not self.id:
            self.added_on = datetime.now()
        self.modified_on = datetime.now()
        return super(DeviceServiceConfiguration, self).save(*args, **kwargs)

    def __unicode__(self):
        """
        Device Service Configuration object presentation
        """
        return "{} - {} - {}".format(self.device_name, self.service_name, self.added_on)


# device service configuration --> it contains services those are already running
class DevicePingConfiguration(models.Model):
    """
    Device Ping Configuration Model Declaration.
    """
    device_name = models.CharField('Device Name', max_length=200, null=True, blank=True)
    device_alias = models.CharField('Device Alias', max_length=200, null=True, blank=True)
    packets = models.IntegerField('Packets', null=True, blank=True)
    timeout = models.IntegerField('Timeout', null=True, blank=True)
    normal_check_interval = models.IntegerField('Normal Check Interval', null=True, blank=True)
    rta_warning = models.IntegerField('RTA Warning', null=True, blank=True)
    rta_critical = models.IntegerField('RTA Critical', null=True, blank=True)
    pl_warning = models.IntegerField('PL Warning', null=True, blank=True)
    pl_critical = models.IntegerField('PL Critical', null=True, blank=True)
    added_on = models.DateTimeField('Added On', null=True, blank=True)
    modified_on = models.DateTimeField('Modified On', null=True, blank=True)

    class Meta:
        ordering = ["added_on"]

    def save(self, *args, **kwargs):
        """ On save, update timestamps """
        if not self.id:
            self.added_on = datetime.now()
        self.modified_on = datetime.now()
        return super(DevicePingConfiguration, self).save(*args, **kwargs)

    def __unicode__(self):
        """
        Device Ping Configuration object presentation
        """
        return "{} - {} - {}".format(self.device_name, self.service_name, self.added_on)

nocout/service/templates/service/service_attributes.html
{{ sds_fromset.management_form }}
{% for sds in service_data_sources %}
    {% for field in sds_fromset %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}" class="col-sm-3 control-label"> Service Data Sources</label>
            <div class="col-sm-9">
                <div class="col-md-8" style="color:#5e87b0;">
                    {{ field.service_data_sources }}
                    {{ field.service_data_sources.value|default_if_none:sds.service_data_sources__name }}
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="{{ field.id_for_label }}" class="col-sm-3 control-label">Warning</label>
            <div class="col-sm-9">
                <div class="col-md-8">
                    {{field.warning}}( {{field.warning.value|default_if_none:sds.warning }} )
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="{{ field.id_for_label }}" class="col-sm-3 control-label">Critical</label>
            <div class="col-sm-9">
                <div class="col-md-8">
                    {{field.critical}}( {{field.warning.value|default_if_none:sds.critical }} )
                </div>
            </div>
        </div>
    {% endfor %}
{% endfor %}

nocout/service/templates/service/service_attributes1.html
{{ service_data_formset.management_form }}
{% for form in service_data_formset %}
    <input type="hidden" name='dts-{{service_counter}}-sds_counter' value="{{counter}}">
    {{form.id}}
    <div class="form-group">
        <label for="{{ form.id_for_label }}" class="col-sm-3 control-label"><span class="mandatory">*</span> Service Data Sources</label>
        <div class="col-sm-9">
            <div class="col-md-7">
                {{form.service_data_sources}}
                {{ service_data_formset.non_form_errors }}
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="{{ form.id_for_label }}" class="col-sm-3 control-label">Warning</label>
        <div class="col-sm-9">
            <div class="col-md-7">
                {{form.warning}}
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="{{ form.id_for_label }}" class="col-sm-3 control-label">Critical</label>
        <div class="col-sm-9">
            <div class="col-md-7">
                {{form.critical}}
            </div>
        </div>
    </div>
{% endfor %}

nocout/service/templates/service/service_attributes_dtsds.html
{{ service_data_formset.management_form }}
{% for form in service_data_formset %}
    <input type="hidden" name='dts-{{service_counter}}-sds_counter' value="{{counter}}">
    {{form.id}}
    <div class="form-group">
        <label for="{{ form.id_for_label }}" class="col-sm-3 control-label"><span class="mandatory">*</span> Service Data Sources</label>
        <div class="col-sm-9">
            <div class="col-md-7">
                {{form.service_data_sources}}
                {{ service_data_formset.non_form_errors }}
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="{{ form.id_for_label }}" class="col-sm-3 control-label">Warning</label>
        <div class="col-sm-9">
            <div class="col-md-7">
                {{form.warning}}
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="{{ form.id_for_label }}" class="col-sm-3 control-label">Critical</label>
        <div class="col-sm-9">
            <div class="col-md-7">
                {{form.critical}}
            </div>
        </div>
    </div>
{% endfor %}

nocout/service/templates/service/service_delete.html
{% extends "inventory/inventory.html" %}

{% block content_title %}Delete Service{% endblock %}
{% block content_description %}Delete service{% endblock %}
{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm"/>
    </form>
{% endblock %}

nocout/service/templates/service/service_detail.html
{% extends "inventory/inventory.html" %}
{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" type="text/css" href={% static "css/service.css" %}>
{% endblock %}

{% block content_title %}Service Detail{% endblock %}
{% block content_description %}Detail of service{% endblock %}
{% block content %}
    <h1>{{ object.service_name }}</h1><br/>
    <div id="service">
        <table>
            <tr>
                <td><strong>Service Name:</strong></td>
                <td>{{ object.service_name }}</td>
            </tr>
            <tr>
                <td><strong>Service Alias:</strong></td>
                <td>{{ object.alias }}</td>
            </tr>
            <tr>
                <td><strong>Service Parameters:</strong></td>
                {% for parameter in object.parameters.all %}
                    <td>{{ parameter }}</td>
                {% endfor %}
            </tr>
            <tr>
                <td><strong>Service Command:</strong></td>
                <td>{{ object.command }}</td>
            </tr>
            <tr>
                <td><strong>Service Description:</strong></td>
                <td>{{ object.description }}</td>
            </tr>
        </table>
    </div>
{% endblock %}

nocout/service/templates/service/service_new.html
{% extends "inventory/inventory.html" %}
{% load staticfiles %}

{% block content_title %}Add Service{% endblock %}
{% block content_description %}Add service{% endblock %}
{% block content %}
    <div class="row formContainer">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="box border lite">
                        <div class="box-title">
                            <h4><i class="fa fa-bars"></i> ADD SERVICE</h4>
                        </div>
                            <div class="box-body">
                                <div class="col-md-8"><br />
                                    <form action="/service/new/" method="post" class="form-horizontal" role="form">{% csrf_token %}
                                        <div class="form-group">
                                            {% for field in form %}
                                                <div class="form-group">
                                                    <label for="{{ field.id_for_label }}" class="col-sm-3 control-label">{% if field.field.required %}<span class="mandatory">* </span>{% endif %}{{ field.label|title }}</label>
                                                    <div class="col-sm-9">
                                                        <div class="col-md-8">
                                                            {{ field }} {{ field.errors }}
                                                        </div>
                                                        <div class="col-md-4 help_text">
                                                            {{ field.help_text }}
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                            {{ service_data_form.management_form }}
                                            {% for field in service_data_form %}
                                            <div class="row inline {{ service_data_form.prefix }}">
                                                <div class="form-group">
                                                    <label for="{{ field.id_for_label }}" class="col-sm-3 control-label"><span class="mandatory">*</span> Service Data Sources</label>
                                                    <div class="col-sm-9">
                                                        <div class="col-md-8">
                                                            {{field.service_data_sources}}{{ service_data_form.non_form_errors }}
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label for="{{ field.id_for_label }}" class="col-sm-3 control-label">Warning</label>
                                                    <div class="col-sm-9">
                                                        <div class="col-md-7">
                                                            {{field.warning}}<label id="id_value">( {{ field.warning.value|default_if_none:"None" }} )</label>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label for="{{ field.id_for_label }}" class="col-sm-3 control-label">Critical</label>
                                                    <div class="col-sm-9">
                                                        <div class="col-md-7">
                                                            {{field.critical}}<label id="id_value">( {{ field.critical.value|default_if_none:"None" }} )</label>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            {% endfor %}
                                        </div>

                                        <div class="form-group">
                                            <div class="col-sm-offset-3 col-sm-9">
                                                <button type="submit" class="btn btn-success"><i class="fa fa-pencil"></i>Create</button>
                                                &nbsp;
                                                <button type="reset" class="btn btn-warning" onclick="resetForm();"><i class="fa fa-refresh"></i>Reset</button>
                                                &nbsp;
                                                <button type="reset" class="btn btn-danger" onclick="window.location.replace('/service/')"><i class="fa fa-times"></i>Cancel</button>
                                            </div>
                                        </div>

                                    </form>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block content_js %}
        <script type="text/javascript" src={% static "js/nocout/nocout_forms.js" %}></script>
        <script type="text/javascript" src={% static "js/service.js" %}></script>
        <script type="text/javascript" src={% static "js/jquery.formset.js" %}></script>
    {% endblock %}
    <script>
        $(document).ready(function(){
            // Initialize the select2 selectbox.
            $(".select2select").select2();

            // if srvice data source is already selected
            var sds = $('form select[name|="servicespecificdatasource_set"]')
            if (sds.length){
                sds.each(function() {
                var sds_id = $(this).find("option:selected").val()
                var sds_location = $(this).parents(".row .inline")
                get_sds_value(sds_id, sds_location)
                })
            }

            // if the data source is changed by the user
            $('form select[name|="servicespecificdatasource_set"]').change(function() {
                var sds_id = $(this).find("option:selected").val()
                var sds_location = $(this).parents(".row .inline")
                get_sds_value(sds_id, sds_location)
            })

            //  Get the value of the data source selected by the user.
            function get_sds_value(sds_id, sds_location){
                var sds_id = sds_id
                if (!sds_id.length){
                    console.log("No service data source is selected")
                }
                else{
                    $.ajax({
                        url : "/service/select/value/data_source/",
                        type : "GET",
                        dataType: "json",
                        data: {
                            sds_id : sds_id,
                        },
                        success : function(sds) {
                            var p = sds_location.children().slice(1)
                            var w = sds.sds_values_list[0]['warning']
                            var c = sds.sds_values_list[0]['critical']
                            // if the data source is empty
                            if (!w.length){ w = null }
                            if (!c.length){ c = null }
                            p.find('[id="id_value"]').remove()
                            p.first().find('input').parent().append('<label id="id_value">( '+w+' )</label>')

                            p.last().find('input').parent().append('<label id="id_value">( '+c+' )</label>')
                        },
                        error : function(xhr,errmsg,err) {
                            console.log(xhr.status + ": " + xhr.responseText);
                        }
                    });

                    return false;
                }
            }
        })
    </script>
    <script type="text/javascript">
       $(function() {
           $(".inline.{{ service_data_form.prefix }}").formset({
               prefix: "{{ service_data_form.prefix }}",
           })
       })
    </script>

{% endblock %}

nocout/service/templates/service/service_parameter_delete.html
{% extends "inventory/inventory.html" %}
{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm"/>
    </form>
{% endblock %}

nocout/service/templates/service/service_parameter_detail.html
{% extends "inventory/inventory.html" %}
{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" type="text/css" href={% static "css/service.css" %}>
{% endblock %}
{% block content %}
    <h1>{{ object.parameter_description }}</h1><br/>
    <div id="service">
        <table>
            <tr>
                <td><strong>Parameter Description:</strong></td>
                <td>{{ object.parameter_description }}</td>
            </tr>
            <tr>
                <td><strong>Max Check Attempts:</strong></td>
                <td>{{ object.max_check_attempts }}</td>
            </tr>
            <tr>
                <td><strong>Check Interval:</strong></td>
                <td>{{ object.check_interval }}</td>
            </tr>
            <tr>
                <td><strong>Retry Interval:</strong></td>
                <td>{{ object.retry_interval }}</td>
            </tr>
            <tr>
                <td><strong>Check Period:</strong></td>
                <td>{{ object.check_period }}</td>
            </tr>
            <tr>
                <td><strong>Notification Interval:</strong></td>
                <td>{{ object.notification_interval }}</td>
            </tr>
            <tr>
                <td><strong>Notification Period:</strong></td>
                <td>{{ object.notification_period }}</td>
            </tr>
        </table>
    </div>
{% endblock %}

nocout/service/templates/service/service_parameter_new.html
{% extends "inventory/inventory.html" %}
{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" type="text/css" href={% static "css/service.css" %}>
{% endblock %}
{% block content %}
    <h3>Create Service Parameters</h3>
    <form action="/sp/new/" method="post">{% csrf_token %}
        <div id="new_service">
            <table>
                <tr>
                    <td>
                        {{ form.errors }}
                        {{ form.non_field_errors }}
                    </td>
                </tr>
                <tr>
                    <th><label for="id_parameter_description"> Parameter Description:</label></th>
                    <td>{{ form.parameter_description }}</td>
                </tr>
                <tr>
                    <th><label for="id_max_check_attempts">Max Check Attempts:</label></th>
                    <td>{{ form.max_check_attempts }}</td>
                </tr>
                <tr>
                    <th><label for="id_check_interval">Check Interval:</label></th>
                    <td>{{ form.check_interval }}</td>
                </tr>
                <tr>
                    <th><label for="id_retry_interval">Retry Interval:</label></th>
                    <td>{{ form.retry_interval }}</td>
                </tr>
                <tr>
                    <th><label for="id_check_period">Check Period:</label></th>
                    <td>{{ form.check_period }}</td>
                </tr>
                <tr>
                    <th><label for="id_notification_interval">Notification Interval:</label></th>
                    <td>{{ form.notification_interval }}</td>
                </tr>
                <tr>
                    <th><label for="id_notification_period">Notification Period:</label></th>
                    <td>{{ form.notification_period }}</td>
                </tr>
                <tr>
                    <th></th>
                    <td><input type="submit" value="Create"/></td>
                </tr>
            </table>
        </div>
    </form>
{% endblock %}

nocout/service/templates/service/service_parameter_update.html
{% extends "inventory/inventory.html" %}
{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" type="text/css" href={% static "css/service.css" %}>
{% endblock %}
{% block content %}
    <h3>Update Service Parameters: {{ object.parameter_description }}</h3>
    <form action="" method="post">{% csrf_token %}
        <div id="new_service">
            <table>
                <tr>
                    <td>
                        {{ form.errors }}
                        {{ form.non_field_errors }}
                    </td>
                </tr>
                <tr>
                    <th><label for="id_parameter_description"> Parameter Description:</label></th>
                    <td>{{ form.parameter_description }}</td>
                </tr>
                <tr>
                    <th><label for="id_max_check_attempts">Max Check Attempts:</label></th>
                    <td>{{ form.max_check_attempts }}</td>
                </tr>
                <tr>
                    <th><label for="id_check_interval">Check Interval:</label></th>
                    <td>{{ form.check_interval }}</td>
                </tr>
                <tr>
                    <th><label for="id_retry_interval">Retry Interval:</label></th>
                    <td>{{ form.retry_interval }}</td>
                </tr>
                <tr>
                    <th><label for="id_check_period">Check Period:</label></th>
                    <td>{{ form.check_period }}</td>
                </tr>
                <tr>
                    <th><label for="id_notification_interval">Notification Interval:</label></th>
                    <td>{{ form.notification_interval }}</td>
                </tr>
                <tr>
                    <th><label for="id_notification_period">Notification Period:</label></th>
                    <td>{{ form.notification_period }}</td>
                </tr>
                <tr>
                    <th></th>
                    <td><input type="submit" value="Update"/></td>
                </tr>
            </table>
        </div>
    </form>
{% endblock %}

nocout/service/templates/service/services_parameter_list.html
{% extends "inventory/inventory.html" %}
{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" type="text/css" href={% static "css/service.css" %}>
{% endblock %}
{% block content %}
    <h2>Service Parameters</h2>
    <hr/>
    <p><a href="/sp/new">Create Service Parameter</a></p>
    <br/>
    <div id="service">
        <table>
            <tr>
                <td><strong>Service Parameters</strong></td>
                <td><strong>Edit</strong></td>
                <td><strong>Delete</strong></td>
            </tr>
            {% for parameter in object_list %}
                <tr>
                    <td><a href="/sp/{{ parameter.id }}">{{ parameter.parameter_description }}</a></td>
                    <td><a href="/sp/edit/{{ parameter.id }}">Edit</a></td>
                    <td><a href="/sp/delete/{{ parameter.id }}">Delete</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}