nocout/device/urls.py
from django.conf.urls import patterns, url
from device import views, api

#caching GIS maps
from django.views.decorators.cache import cache_page
#caching GIS maps

urlpatterns = patterns('',
  url(r'^$', views.DeviceList.as_view(), name='device_list'),
  url(r'^(?P<pk>\d+)/$', views.DeviceDetail.as_view(), name='device_detail'),
  url(r'^new/$', views.DeviceCreate.as_view(), name='device_new'),
  url(r'^(?P<pk>\d+)/edit/$', views.DeviceUpdate.as_view(), name='device_edit'),
  url(r'^(?P<pk>\d+)/delete/$', views.DeviceDelete.as_view(), name='device_delete'),

  # url(r'^stats/$', cache_page(60 * 60)(api.DeviceStatsApi.as_view())),
  url(r'^stats/$', api.DeviceStatsApi.as_view()),

  #cache the Filters. they dont change
  url(r'^filter/$', cache_page(60 * 60)(api.DeviceFilterApi.as_view())),
  #cache the Filters. they dont change

  url(r'^lp_services/', api.LPServicesApi.as_view()),
  url(r'^lp_service_data/', api.FetchLPDataApi.as_view()),
  url(r'^lp_bulk_data/', api.BulkFetchLPDataApi.as_view()),
  url(r'^ts_templates/', api.FetchThematicSettingsApi.as_view()),
  url(r'^treeview/$', views.create_device_tree, name='device_tree_view'),
  url(r'^operationaldevicelistingtable/', views.OperationalDeviceListingTable.as_view(), name= 'OperationalDeviceListingTable'),
  url(r'^nonoperationaldevicelistingtable/', views.NonOperationalDeviceListingTable.as_view(), name= 'NonOperationalDeviceListingTable'),
  url(r'^disableddevicelistingtable/', views.DisabledDeviceListingTable.as_view(), name= 'DisabledDeviceListingTable'),
  url(r'^archiveddevicelistingtable/', views.ArchivedDeviceListingTable.as_view(), name= 'ArchivedDeviceListingTable'),
  url(r'^alldevicelistingtable/', views.AllDeviceListingTable.as_view(), name= 'AllDeviceListingTable'),
)

nocout/device/models.py
from django.db import models
from machine.models import Machine
from organization.models import Organization
from site_instance.models import SiteInstance
from service.models import Service, ServiceParameters, ServiceDataSource
from mptt.models import MPTTModel


#************************************ Device Inventory**************************************
# table for countries
class Country(models.Model):
    country_name = models.CharField('Name', max_length=200)

    def __unicode__(self):
        return self.country_name


# table for states
class State(models.Model):
    state_name = models.CharField('Name', max_length=200)
    country = models.ForeignKey(Country, null=True, blank=True)

    def __unicode__(self):
        return self.state_name


# table for cities
class City(models.Model):
    city_name = models.CharField('Name', max_length=250)
    state = models.ForeignKey(State, null=True, blank=True)

    def __unicode__(self):
        return self.city_name


# table for state latitude & longitude
class StateGeoInfo(models.Model):
    state = models.ForeignKey(State)
    latitude = models.FloatField('Latitude')
    longitude = models.FloatField('Longitude')


class DeviceFrequency(models.Model):
    value = models.CharField(max_length=50, help_text="MHz")
    color_hex_value = models.CharField(max_length=100)
    frequency_radius = models.FloatField(verbose_name="Frequency Radius", default=0, help_text="Km")

    def __unicode__(self):
        return self.value


# device ports
class DevicePort(models.Model):
    name = models.CharField('Name', max_length=100, unique=True)
    alias = models.CharField('Alias', max_length=200)
    value = models.IntegerField('Port Value', default=0)

    def __unicode__(self):
        return self.name


# device types info table
class DeviceType(models.Model):
    name = models.CharField('Device Type', max_length=200, unique=True)
    alias = models.CharField('Alias', max_length=200)
    device_port = models.ManyToManyField(DevicePort, null=True, blank=True)
    service = models.ManyToManyField(Service, through="DeviceTypeService", blank=True, null=True)
    packets = models.IntegerField('Packets', blank=True, null=True)
    timeout = models.IntegerField('Timeout', blank=True, null=True)
    normal_check_interval = models.IntegerField('Normal Check Interval', blank=True, null=True)
    rta_warning = models.IntegerField('RTA Warning', blank=True, null=True)
    rta_critical = models.IntegerField('RTA Critical', blank=True, null=True)
    pl_warning = models.IntegerField('PL Warning', blank=True, null=True)
    pl_critical = models.IntegerField('PL Critical', blank=True, null=True)
    agent_tag = models.CharField('Agent Tag', max_length=200, null=True, blank=True)
    device_icon = models.ImageField(upload_to='uploaded/icons/%Y/%m/%d')
    device_gmap_icon = models.ImageField(upload_to='uploaded/icons/%Y/%m/%d')

    def __unicode__(self):
        return self.name

    def delete(self, *args, **kwargs):
        """
        Delete method: deletes the device_icon and device_gmap_icon.
        """
        self.device_icon.delete()
        self.device_gmap_icon.delete()
        super(DeviceType, self).delete(*args, **kwargs)


# device type with specific service info table
class DeviceTypeService(models.Model):
    device_type = models.ForeignKey(DeviceType)
    service = models.ForeignKey(Service)
    parameter = models.ForeignKey(ServiceParameters)
    service_data_sources = models.ManyToManyField(ServiceDataSource, through="DeviceTypeServiceDataSource")


# device type with specific service data source info table
class DeviceTypeServiceDataSource(models.Model):
    device_type_service = models.ForeignKey(DeviceTypeService)
    service_data_sources = models.ForeignKey(ServiceDataSource)
    warning = models.CharField('Warning', max_length=255, null=True, blank=True)
    critical = models.CharField('Critical', max_length=255, null=True, blank=True)


# device model info table
class DeviceModel(models.Model):
    name = models.CharField('Device Model', max_length=100, unique=True)
    alias = models.CharField('Alias', max_length=200)
    device_types = models.ManyToManyField(DeviceType, through="ModelType", blank=True, null=True)

    def __unicode__(self):
        return self.name


# device vendor info table
class DeviceVendor(models.Model):
    name = models.CharField('Device Vendor', max_length=100, unique=True)
    alias = models.CharField('Alias', max_length=200)
    device_models = models.ManyToManyField(DeviceModel, through="VendorModel", blank=True, null=True)

    def __unicode__(self):
        return self.name


# device technology info table
class DeviceTechnology(models.Model):
    name = models.CharField('Device Technology', max_length=100, unique=True)
    alias = models.CharField('Alias', max_length=200)
    device_vendors = models.ManyToManyField(DeviceVendor, through="TechnologyVendor", blank=True, null=True)

    def __unicode__(self):
        return self.name


# device info table
class Device(MPTTModel, models.Model):
    enable = 'Enable'
    disable = 'Disable'
    high = 'High'
    normal = 'Normal'
    low = 'Low'

    DHCP_STATE = (
        (enable, 'Enable'),
        (disable, 'Disable'),
    )
    HOST_STATE = (
        (enable, 'Enable'),
        (disable, 'Disable'),
    )
    PRIORITY = (
        (high, 'High'),
        (normal, 'Normal'),
        (low, 'Low')
    )

    device_name = models.CharField('Name', max_length=200, unique=True)
    device_alias = models.CharField('Alias', max_length=200)
    machine = models.ForeignKey(Machine, null=True, blank=True)
    site_instance = models.ForeignKey(SiteInstance, null=True, blank=True)
    organization = models.ForeignKey(Organization)
    device_technology = models.IntegerField('Device Technology')
    device_vendor = models.IntegerField('Device Vendor')
    device_model = models.IntegerField('Device Model')
    device_type = models.IntegerField('Device Type')
    ports = models.ManyToManyField(DevicePort, null=True, blank=True)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='device_children')
    ip_address = models.IPAddressField('IP Address', unique=True)
    mac_address = models.CharField('MAC Address', max_length=100, null=True, blank=True)
    netmask = models.IPAddressField('Netmask', null=True, blank=True)
    gateway = models.IPAddressField('Gateway', null=True, blank=True)
    dhcp_state = models.CharField('DHCP State', max_length=200, choices=DHCP_STATE, default=disable)
    host_priority = models.CharField('Host Priority', max_length=200, choices=PRIORITY, default=normal)
    host_state = models.CharField('Host Monitoring State', max_length=200, choices=HOST_STATE, default=enable)
    latitude = models.FloatField('Latitude', null=True, blank=True)
    longitude = models.FloatField('Longitude', null=True, blank=True)
    timezone = models.CharField('Timezone', max_length=100, default="Asia/Kolkata")
    country = models.IntegerField('Country', null=True, blank=True)
    state = models.IntegerField('State', null=True, blank=True)
    city = models.IntegerField('City', null=True, blank=True)
    address = models.TextField('Address', null=True, blank=True)
    description = models.TextField('Description', null=True, blank=True)
    is_deleted = models.IntegerField('Is Deleted', max_length=1, default=0)
    is_added_to_nms = models.IntegerField('Is Added', max_length=1, default=0)
    is_monitored_on_nms = models.IntegerField('Is Monitored', max_length=1, default=0)

    def __unicode__(self):
        return self.device_alias

    class Meta:
        ordering = ['machine']


# model-type mapper
class ModelType(models.Model):
    model = models.ForeignKey(DeviceModel)
    type = models.ForeignKey(DeviceType)


# vendor-model mapper
class VendorModel(models.Model):
    vendor = models.ForeignKey(DeviceVendor)
    model = models.ForeignKey(DeviceModel)


# technology-vendor mapper
class TechnologyVendor(models.Model):
    technology = models.ForeignKey(DeviceTechnology)
    vendor = models.ForeignKey(DeviceVendor)


# table for extra fields of device (depends upon device type)
class DeviceTypeFields(models.Model):
    field_name = models.CharField(max_length=100)
    field_display_name = models.CharField(max_length=200)
    device_type = models.ForeignKey(DeviceType)

    def __unicode__(self):
        return self.field_display_name


# table for device extra fields values
class DeviceTypeFieldsValue(models.Model):
    device_type_field = models.ForeignKey(DeviceTypeFields)
    field_value = models.CharField(max_length=250)
    device_id = models.IntegerField()

nocout/device/templates/device_vendor/device_vendor_delete.html
{% extends "inventory/inventory.html" %}

{% block content_title %}Delete Device Vendor{% endblock %}
{% block content_description %}Delete device vendor{% endblock %}
{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm"/>
    </form>
{% endblock %}

nocout/device/templates/device_vendor/device_vendor_detail.html
{% extends "inventory/inventory.html" %}
{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" type="text/css" href={% static "css/device.css" %}>
{% endblock %}

{% block content_title %}Device Vendor Detial{% endblock %}
{% block content_description %}Detail of device vendor{% endblock %}
{% block content %}
    <h1>{{ object.name }}</h1><br/>
    <div id="device">
        <table>
            <tr>
                <td><strong>Vendor Name:</strong></td>
                <td>{{ object.name }}</td>
            </tr>
            <tr>
                <td><strong>Vendor Alias:</strong></td>
                <td>{{ object.alias }}</td>
            </tr>
            <tr>
                <td><strong>Vendor Models:</strong></td>
                {% for model in object.vendormodel_set.all %}
                    <td>{{ model.model }}</td>
                {% endfor %}
            </tr>
        </table>
    </div>
{% endblock %}

nocout/device/templates/device_vendor/device_vendor_list.html
{% extends "inventory/inventory.html" %}
{% load staticfiles %}

{% block content_title %}Device Vendor Management{% endblock %}
{% block content_description %}List of device vendor{% endblock %}
{% block content %}
    <p><a href="/vendor/new"><i class="fa fa-plus">&nbsp;</i> Create Device Vendor</a></p>
    <div class="box border lite">
        <div id="tableContainer_div" class="box-title">
            <h4><i class="fa fa-table"></i> DEVICE VENDOR LISTING</h4>
{#            <div class="tools hidden-xs">#}
{#                <a href="#box-config" data-toggle="modal" class="config">#}
{#                    <i class="fa fa-cog"></i>#}
{#                </a>#}
{#                <a href="javascript:;" class="reload">#}
{#                    <i class="fa fa-refresh"></i>#}
{#                </a>#}
{#            </div>#}
        </div>

        <div id="tableContainer" class="box-body">
            <table cellpadding="0" cellspacing="0" border="0" class="datatable table table-striped table-bordered table-hover" id="DeviceVendorListingTable">
                <thead></thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block jquery %}
    <script type="text/javascript" src={% static "js/utils/jqueryDataTable.js" %}></script>
    <script type="text/javascript">
        $(document).ready(function (e) {
            /*Make a instance of ourDataTableWidget class */
            var dataTableInstance = new ourDataTableWidget();
            /*Grid headers object*/
            var gridHeadersObj = $.parseJSON('{{ datatable_headers|safe }}');
            /*Ajax url to get grid data*/
            var ajax_url = '{% url "DeviceVendorListingTable" %}';
            /*Call createDataTable function of ourDataTableWidget class*/
            var destroy=false;
            dataTableInstance.createDataTable("DeviceVendorListingTable", gridHeadersObj, ajax_url, destroy);
        });
    </script>
{% endblock %}

nocout/device/templates/device_vendor/device_vendor_new.html
{% extends "inventory/inventory.html" %}
{% load staticfiles %}

{% block content_title %}Add Device Vendor{% endblock %}
{% block content_description %}Add device vendor{% endblock %}
{% block content %}
    <div class="row formContainer">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="box border lite">
                        <div class="box-title">
                            <h4><i class="fa fa-bars"></i> ADD DEVICE VENDOR</h4>
                        </div>
                            <div class="box-body">
                                <div class="col-md-8"><br />
                                    <form action="/vendor/new/" method="post" class="form-horizontal" role="form">{% csrf_token %}
                                        <div class="form-group">
                                            {% for field in form %}
                                                <div class="form-group">
                                                    <label for="{{ field.id_for_label }}" class="col-sm-3 control-label">{% if field.field.required %}<span class="mandatory">* </span>{% endif %}{{ field.label|title }}</label>
                                                    <div class="col-sm-9">
                                                        <div class="col-md-8">
                                                            {{ field }} {{ field.errors }}
                                                        </div>
                                                        <div class="col-md-4 help_text">
                                                            {{ field.help_text }}
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                        <div class="form-group">
                                            <div class="col-sm-offset-3 col-sm-9">
                                                <button type="submit" class="btn btn-success"><i class="fa fa-pencil"></i>Create</button>
                                                &nbsp;
                                                <button type="reset" class="btn btn-warning" onclick="resetForm();"><i class="fa fa-refresh"></i>Reset</button>
                                                &nbsp;
                                                <button type="reset" class="btn btn-danger" onclick="window.location.replace('/vendor/')"><i class="fa fa-times"></i>Cancel</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block content_js %}
        <script type="text/javascript" src={% static "js/nocout/nocout_forms.js" %}></script>
    {% endblock %}
    <script>
        $(document).ready(function(){
            // Initialize the select2 selectbox.
            $(".select2select").select2();
        })
    </script>
{% endblock %}

nocout/device/templates/device_vendor/device_vendor_update.html
{% extends "inventory/inventory.html" %}
{% load staticfiles %}

{% block content_title %}Edit Device Vendor{% endblock %}
{% block content_description %}Edit device vendor{% endblock %}
{% block content %}
    <div class="row formContainer">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="box border lite">
                        <div class="box-title">
                            <h4><i class="fa fa-bars"></i> EDIT DEVICE VENDOR : {{ object.name }}</h4>
                        </div>
                            <div class="box-body">
                                <div class="col-md-8"><br />
                                    <form action="" method="post" class="form-horizontal" role="form">{% csrf_token %}
                                        <div class="form-group">
                                            {% for field in form %}
                                                <div class="form-group">
                                                    <label for="{{ field.id_for_label }}" class="col-sm-3 control-label">{% if field.field.required %}<span class="mandatory">* </span>{% endif %}{{ field.label|title }}</label>
                                                    <div class="col-sm-9">
                                                        <div class="col-md-8">
                                                            {{ field }} {{ field.errors }}
                                                        </div>
                                                        <div class="col-md-4 help_text">
                                                            {{ field.help_text }}
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                        <div class="form-group">
                                            <div class="col-sm-offset-3 col-sm-9">
                                                <button type="submit" class="btn btn-info"><i class="fa fa-edit"></i> Update</button>
                                                &nbsp;
                                                <button type="reset" class="btn btn-danger" onclick="window.location.replace('/vendor/')"><i class="fa fa-times"></i> Cancel</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block content_js %}
        <script type="text/javascript" src={% static "js/nocout/nocout_forms.js" %}></script>
    {% endblock %}
    <script>
        $(document).ready(function(){
            // Initialize the select2 selectbox.
            $(".select2select").select2();
        })
    </script>
{% endblock %}